# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chenjianzhong', '0003_auto_20151229_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='begin',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 31, 16, 33, 19, 406681, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 31, 16, 33, 22, 990666, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='present',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
