# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chenjianzhong', '0004_auto_20151231_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(default='Role', max_length=200),
            preserve_default=False,
        ),
    ]
